"use client";

import { Download } from "lucide-react";

interface StudentAttendance {
    name: string;
    sin?: string;
    year_level?: string;
    status: string;
    timeIn: string;
    timeOut: string;
}

interface ExportCSVButtonProps {
    className_: string;
    date: string;
    students: StudentAttendance[];
}

export function ExportCSVButton({ className_, date, students }: ExportCSVButtonProps) {
    const handleExport = () => {
        // CSV Header
        const headers = ["Student Name", "SIN", "Year Level", "Status", "Time In", "Time Out"];

        // CSV Rows
        const rows = students.map(s => [
            `"${s.name}"`,
            s.sin || "N/A",
            s.year_level || "N/A",
            s.status,
            s.timeIn,
            s.timeOut,
        ]);

        // Summary row
        const present = students.filter(s => s.status === "Present").length;
        const late = students.filter(s => s.status === "Late").length;
        const absent = students.filter(s => ["Absent", "Cut Class", "Ghosting"].includes(s.status)).length;
        const excused = students.filter(s => s.status === "Excused").length;

        const csv = [
            `ClassTrack Attendance Export`,
            `Class: ${className_}`,
            `Date: ${date}`,
            `Total Students: ${students.length}`,
            `Present: ${present} | Late: ${late} | Excused: ${excused} | Absent: ${absent}`,
            ``,
            headers.join(","),
            ...rows.map(r => r.join(",")),
            ``,
            `Generated by ClassTrack — ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`,
        ].join("\n");

        // Trigger download
        const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${className_.replace(/\s+/g, "_")}_${date}.csv`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <button
            onClick={handleExport}
            className="px-3 py-1.5 text-xs font-bold text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 transition-all flex items-center gap-1.5 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-700"
            title="Download attendance as CSV"
        >
            <Download className="h-3.5 w-3.5" />
            Export CSV
        </button>
    );
}
