"use client";

import { FileSpreadsheet } from "lucide-react";

interface StudentFullReport {
    name: string;
    sin?: string;
    year_level?: string;
    totalSessions: number;
    presentCount: number;
    lateCount: number;
    absentCount: number;
    excusedCount: number;
    attendanceRate: number;
}

interface ExportFullReportButtonProps {
    className_: string;
    students: StudentFullReport[];
}

export function ExportFullReportButton({ className_, students }: ExportFullReportButtonProps) {
    const handleExport = () => {
        const headers = ["Student Name", "SIN", "Year Level", "Total Sessions", "Present", "Late", "Absent", "Excused", "Attendance %"];

        const rows = students
            .sort((a, b) => a.attendanceRate - b.attendanceRate) // Worst first
            .map(s => [
                `"${s.name}"`,
                s.sin || "N/A",
                s.year_level || "N/A",
                s.totalSessions,
                s.presentCount,
                s.lateCount,
                s.absentCount,
                s.excusedCount,
                `${s.attendanceRate.toFixed(1)}%`,
            ]);

        const avgRate = students.length > 0
            ? (students.reduce((sum, s) => sum + s.attendanceRate, 0) / students.length).toFixed(1)
            : "0";

        const csv = [
            `ClassTrack — Full Attendance Report`,
            `Class: ${className_}`,
            `Total Students: ${students.length}`,
            `Class Average Attendance: ${avgRate}%`,
            `Generated On: ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`,
            ``,
            headers.join(","),
            ...rows.map(r => r.join(",")),
            ``,
            `Generated by ClassTrack Attendance System`,
        ].join("\n");

        const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${className_.replace(/\s+/g, "_")}_Full_Report.csv`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <button
            onClick={handleExport}
            className="px-3 py-1.5 text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-lg hover:bg-indigo-100 transition-all flex items-center gap-1.5 dark:bg-indigo-900/20 dark:text-indigo-400 dark:border-indigo-800 dark:hover:bg-indigo-900/40"
            title="Download full attendance summary (all dates)"
        >
            <FileSpreadsheet className="h-3.5 w-3.5" />
            Full Report
        </button>
    );
}
