"use client";

import { FileSpreadsheet } from "lucide-react";
import { useState } from "react";
import { getDepartmentAttendanceSummary, StudentFullReport } from "./actions";

interface ExportFullReportButtonProps {
    departmentId: string;
    departmentName?: string;
}

export function ExportFullReportButton({ departmentId, departmentName }: ExportFullReportButtonProps) {
    const [loading, setLoading] = useState(false);

    const handleExport = async () => {
        try {
            setLoading(true);
            const data = await getDepartmentAttendanceSummary(departmentId);
            
            if (!data || data.length === 0) {
                alert("No student records found to generate report.");
                return;
            }

            const headers = ["Student Name", "SIN", "Year Level", "Total Sessions", "Present", "Late", "Absent", "Excused", "Attendance %"];

            const rows = data
                .sort((a: StudentFullReport, b: StudentFullReport) => a.attendanceRate - b.attendanceRate) // Worst first
                .map((s: StudentFullReport) => [
                    `"${s.name}"`,
                    s.sin || "N/A",
                    s.year_level || "N/A",
                    s.totalSessions,
                    s.presentCount,
                    s.lateCount,
                    s.absentCount,
                    s.excusedCount,
                    `${s.attendanceRate.toFixed(1)}%`,
                ]);

            const avgRate = data.length > 0
                ? (data.reduce((sum: number, s: StudentFullReport) => sum + s.attendanceRate, 0) / data.length).toFixed(1)
                : "0";

            const csv = [
                `ClassTrack — Full Department Attendance Report`,
                departmentName ? `Department: ${departmentName}` : `Global Report`,
                `Total Students: ${data.length}`,
                `Overall Average Attendance: ${avgRate}%`,
                `Generated On: ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`,
                ``,
                headers.join(","),
                ...rows.map((r: (string | number)[]) => r.join(",")),
                ``,
                `Generated by ClassTrack Attendance System`,
            ].join("\n");

            const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            const filename = departmentName 
                ? `${departmentName.replace(/\s+/g, "_")}_Full_Report.csv`
                : `Global_Full_Report.csv`;
            a.download = filename;
            a.click();
            URL.revokeObjectURL(url);
        } catch (error) {
            console.error("Export failed:", error);
            alert("Failed to generate report. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <button
            onClick={handleExport}
            disabled={loading}
            className={`px-3 py-1.5 text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-lg hover:bg-indigo-100 transition-all flex items-center gap-1.5 dark:bg-indigo-900/20 dark:text-indigo-400 dark:border-indigo-800 dark:hover:bg-indigo-900/40 ${loading ? 'opacity-50 cursor-wait' : ''}`}
            title="Download full attendance summary for all students (cumulative)"
        >
            <FileSpreadsheet className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} />
            {loading ? "Generating..." : "Full Report"}
        </button>
    );
}
