"use client";

import { Download } from "lucide-react";
import { AttendanceRow } from "@/components/LiveAttendanceTable";

interface ExportCSVButtonProps {
    date: string;
    rows: AttendanceRow[];
    departmentName?: string;
}

export function ExportCSVButton({ date, rows, departmentName }: ExportCSVButtonProps) {
    const handleExport = () => {
        const headers = ["Date", "Student Name", "SIN", "Year Level", "Class Name", "Status", "Time In", "Time Out"];

        const csvRows = rows.map(r => [
            r.date ? new Date(r.date).toLocaleDateString() : "-",
            `"${r.studentName}"`,
            r.studentSin || "N/A",
            r.yearLevel || "N/A",
            `"${r.className}"`,
            r.statusLabel,
            r.timeIn,
            r.timeOut,
        ]);

        const present = rows.filter(r => r.statusLabel === "Present").length;
        const late = rows.filter(r => r.statusLabel === "Late").length;
        const absent = rows.filter(r => ["Absent", "Cut Class", "Ghosting", "Absent (No Timeout)"].includes(r.statusLabel)).length;
        const excused = rows.filter(r => r.statusLabel === "Excused").length;

        const csv = [
            `ClassTrack Global Attendance Export`,
            departmentName ? `Department: ${departmentName}` : `Global Report`,
            `Date: ${date}`,
            `Total Records: ${rows.length}`,
            `Present: ${present} | Late: ${late} | Excused: ${excused} | Absent: ${absent}`,
            ``,
            headers.join(","),
            ...csvRows.map(r => r.join(",")),
            ``,
            `Generated by ClassTrack — ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`,
        ].join("\n");

        const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        const filename = departmentName 
            ? `${departmentName.replace(/\s+/g, "_")}_Attendance_${date}.csv`
            : `Global_Attendance_${date}.csv`;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <button
            onClick={handleExport}
            className="px-3 py-1.5 text-xs font-bold text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 transition-all flex items-center gap-1.5 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 dark:hover:bg-gray-700"
            title="Download current view as CSV"
        >
            <Download className="h-3.5 w-3.5" />
            Export CSV
        </button>
    );
}
